// Types: Describen qué es lo que sucede en la aplicación.

/* PRODUCTS */
export const ADD_PRODUCT = "ADD_PRODUCT";
export const SUCCESSFUL_ADDED_PRODUCT = "SUCCESSFUL_ADDED_PRODUCT";
export const UNSUCCESSFUL_ADDED_PRODUCT = "UNSUCCESSFUL_ADDED_PRODUCT";

export const BEGIN_PRODUCTS_DOWNLOAD = "BEGIN_PRODUCTS_DOWNLOAD";
export const SUCCESSFUL_PRODUCTS_DOWNLOAD = "SUCCESSFUL_PRODUCTS_DOWNLOAD";
export const UNSUCCESSFUL_PRODUCTS_DOWNLOAD = "UNSUCCESSFUL_PRODUCTS_DOWNLOAD";

export const GET_PRODUCT_TO_DELETE = "GET_PRODUCT_TO_DELETE";
export const SUCCESSFUL_PRODUCT_DELETION = "SUCCESSFUL_PRODUCT_DELETION";
export const ERROR_DELETING_PRODUCT = "ERROR_DELETING_PRODUCT";

export const GET_PRODUCT_TO_EDIT = "GET_PRODUCT_TO_EDIT";
export const BEGIN_PRODUCT_EDITION = "BEGIN_PRODUCT_EDITION";
export const SUCCESSFUL_PRODUCT_EDITION = "SUCCESSFUL_PRODUCT_EDITION";
export const ERROR_EDITING_PRODUCT = "ERROR_EDITING_PRODUCT";

/* ALERTS */
export const SHOW_ALERT = "SHOW_ALERT";
export const HIDE_ALERT = "HIDE_ALERT";
