// Types: Describen qué es lo que sucede en la aplicación.

/* PRODUCTS */
export const ADD_PRODUCT = "ADD_PRODUCT";
export const SUCCESSFUL_ADDED_PRODUCT = "SUCCESSFUL_ADDED_PRODUCT";
export const UNSUCCESSFUL_ADDED_PRODUCT = "UNSUCCESSFUL_ADDED_PRODUCT";

export const BEGIN_PRODUCTS_DOWNLOAD = "BEGIN_PRODUCTS_DOWNLOAD";
export const SUCCESSFUL_PRODUCTS_DOWNLOAD = "SUCCESSFUL_PRODUCTS_DOWNLOAD";
export const UNSUCCESSFUL_PRODUCTS_DOWNLOAD = "UNSUCCESSFUL_PRODUCTS_DOWNLOAD";
